services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"

  movie-db:
    image: postgres:15
    container_name: movie-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - movie-db-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5433:5432"


  api-gateway-service:
    build:
      context: ../api-gateway
    container_name: api-gateway
    env_file:
      - ../api-gateway/.env
    depends_on:
      - auth-service
      - movie-service
      - rabbitmq
    networks:
      - mynetwork
    ports:
      - "8080:8080"

  auth-service:
    build:
      context: ../auth-service
    container_name: auth-service
    env_file:
      - ../auth-service/.env
    depends_on:
      - auth-db
      - rabbitmq
    networks:
      - mynetwork
    ports:
      - "8081:8081"

  movie-service:
    build:
      context: ../movie-service
    container_name: movie-service
    env_file:
      - ../movie-service/.env
    depends_on:
      - movie-db
      - rabbitmq
    networks:
      - mynetwork
    ports:
      - "8082:8082"

  rabbitmq:
    image: rabbitmq:3-management  # Официальный образ RabbitMQ с Management Plugin
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Порт для приложений RabbitMQ
      - "15672:15672"  # Порт для веб-интерфейса управления
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Установите пользователя по умолчанию
      RABBITMQ_DEFAULT_PASS: guest  # Установите пароль по умолчанию
    networks:
      - mynetwork

volumes:
  auth-db-data:
  movie-db-data:

networks:
  mynetwork:
    driver: bridge
